//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MHSEC_G.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MHSEC_G.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0001	Empty Slot
        ///0002	No Slot
        ///0003	アプトノス遺伝子
        ///0004	ポポ遺伝子
        ///0005	アプケロス遺伝子
        ///0006	怪鳥遺伝子
        ///0007	青怪鳥遺伝子
        ///0008	毒怪鳥遺伝子
        ///0009	紫毒怪鳥遺伝子
        ///000A	黒狼鳥遺伝子
        ///000B	青熊獣遺伝子
        ///000C	白兔獣遺伝子
        ///000D	ドスランポス遺伝子
        ///000E	ドスイーオス遺伝子
        ///000F	ドスゲネポス遺伝子
        ///0010	大猪遺伝子
        ///0011	化け鮫遺伝子
        ///0012	フルフル遺伝子
        ///0013	フルフル亜種遺伝子
        ///0014	轟竜遺伝子
        ///0015	黒轟竜遺伝子
        ///0016	迅竜遺伝子
        ///0017	緑迅竜遺伝子
        ///0018	雌火竜遺伝子
        ///0019	桜火竜遺伝子
        ///001A	金火竜遺伝子
        ///001B	火竜遺伝子
        ///001C	蒼火竜遺伝子
        ///001D	銀火竜遺伝子
        ///001E	隻眼の火竜遺伝子
        ///001F	角竜遺伝子
        ///0020	黒角竜遺伝子
        ///0021	一角竜遺伝子
        ///0022	白一角竜遺伝子
        ///0023	岩竜遺伝子
        ///0024	桃岩竜遺伝子
        ///0025	鎧竜遺伝子
        ///0026	黒鎧竜遺伝子
        ///0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string gene {
            get {
                return ResourceManager.GetString("gene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10	1	药草
        ///18	2	回复药
        ///20	3	回复G
        ///28	4	回复粉
        ///30	5	生命粉
        ///38	6	生命大粉
        ///40	7	秘药
        ///48	16	气合のカタマリ
        ///50	9	活力剂
        ///58	8	いにしえの秘药
        ///60	A	解毒草
        ///68	B	解毒药
        ///70	C	アロエ草
        ///78	D	烧伤药
        ///80	E	マヒワリの花
        ///88	F	麻痹药
        ///90	10	トウガラシ
        ///98	11	元気ドリンコ
        ///A0	12	多肉ニンニク
        ///A8	13	熱血サプリ
        ///B0	14	シャンボン菜
        ///B8	15	爆破落とし洗剤
        ///C0	18	メニーベリー
        ///C8	19	目薬
        ///D0	1A	万能ウチケシ薬
        ///D8	AE	コゲ肉
        ///E0	AF	生焼け肉
        ///E8	B0	こんがり肉
        ///F0	B1	マッスルミート
        ///F8	B2	タフネスミート
        ///100	B3	クィックミート
        ///108	B4	こんがり肉Ｇ
        ///110	1D	ハンタードーナツ
        ///118	1F	ロア・ル・リング
        ///120	20	バルドーナツ
        ///128	21	ドスドーナツ
        ///130	24	ギルドーナツ
        ///138	25	アイルーシュガー
        ///140	26	メラルーショコラ
        ///148	27	こ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string idmap {
            get {
                return ResourceManager.GetString("idmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon MainIcon {
            get {
                object obj = ResourceManager.GetObject("MainIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] monster_null_template {
            get {
                object obj = ResourceManager.GetObject("monster_null_template", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
